CREATE DATABASE IF NOT EXISTS MY_DATABASE;
GRANT ALL PRIVILEGES ON MY_DATABASE.* TO 'MY_USER'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS MY_DATABASE.visitors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(45),
  visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
