- name: Detect boot device
  shell: findmnt -n -o SOURCE /
  register: root_device_result
  when: device == "/dev/sda"
  changed_when: false

- name: Set root partition as device if boot disk
  set_fact:
    device: "{{ root_device_result.stdout }}"
  when: device == "/dev/sda"

- name: Extract disk and partition number
  set_fact:
    base_device: "{{ device | regex_replace('^(/dev/.*?)([0-9]+)$', '\\1') }}"
    part_number: "{{ device | regex_replace('^(/dev/.*?)([0-9]+)$', '\\2') }}"

- name: Run growpart to resize partition
  command: growpart {{ base_device }} {{ part_number }}
  register: growpart_result
  changed_when: false
  failed_when: growpart_result.rc != 0 and 'NOCHANGE' not in growpart_result.stdout

- name: Get filesystem type of partition
  command: lsblk -no FSTYPE {{ device }}
  register: fs_type
  changed_when: false

- name: Resize ext4 filesystem
  command: resize2fs {{ device }}
  when: fs_type.stdout == "ext4"
  changed_when: true

- name: Resize xfs filesystem
  command: xfs_growfs {{ device }}
  when: fs_type.stdout == "xfs"
  changed_when: true
