#cloud-config

users: []

runcmd:
  - mkdir -p /mnt/cdrom
  - mount /dev/sr0 /mnt/cdrom
  - cp /mnt/cdrom/startup.sh /root/startup.sh
  - chmod +x /root/startup.sh
  - /root/startup.sh
  - umount /mnt/cdrom
  - rmdir /mnt/cdrom
  - rm -f /root/startup.sh
