---
- name: Mount disk
  hosts: all
  become: true
  gather_facts: false
  vars:
    device_name: ""
    device: ""
    mount: ""

  tasks:
    - name: Resolve disk device
      ansible.builtin.import_tasks: tasks/resolve_disk_device_tasks.yml

    - name: Mount disk
      ansible.builtin.import_tasks: tasks/mount_disk_tasks.yml
