---
- name: Resize disk
  hosts: all
  become: true
  gather_facts: false
  vars:
    device_name: ""
    device: ""

  tasks:
    - name: Resolve disk device
      ansible.builtin.import_tasks: tasks/resolve_disk_device_tasks.yml

    - name: Resize disk
      ansible.builtin.import_tasks: tasks/resize_disk_tasks.yml
