---
- name: Wait for startup-done.marker on target VM
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Wait for startup script marker file
      ansible.builtin.import_tasks: tasks/wait_for_startup_marker_tasks.yml
